<?php

return [
    [
        'name' => 'Vitello alle arance ',
        'description' =>
        'Carne alla brace',
        'ingredients' => '700 g di arrosto di vitello, 2 arance non trattate, 1 dl di vino bianco, 1/2 dl di brandy, 30 g di burro, 1 foglia di alloro, sale, pepe.',
        'price' => 22.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Costolette di castrato',
        'description' =>
        'Carne cotta alla brace',
        'ingredients' => '700 g di costolette di castrato, cipolla, carota, 3 pomodori, prezzemolo, 1/2 bicchiere di vino rosso, olio, burro.',
        'price' => 25.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Involtini di petto di pollo con speck e provola',
        'description' => 'Gli involtini di petto di pollo con speck e provola sono un gustosissimo secondo piatto a base di pollo.',
        'ingredients' => '300 gr di petto di pollo tagliato in 4 fettine, 100 gr di speck, 60 gr di provola silana o scamorza bianca, 200 ml di vino bianco secco, 1 cucchiaio di olio extravergine di olivamirto (qualche fogliolina) sale e pepe ',
        'price' => 18.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cotoletta alla milanese',
        'description' =>
        'La cotoletta alla milanese è il piatto più famoso e tipico di Milano insieme al risotto alla milanese e al panettone. La cotoletta fritta è presente anche in altre cucine tipiche come quella austriaca dove prende il nome di Wiener Schnitzel o in quella giapponese dove viene chiamata tonkatsu',
        'ingredients' => '4 fette di carne di vitella (costoletta con osso), 2 uova, pangrattato, farina, sale, 300 gr di burro chiarificato',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pasticcio di pollo e patate',
        'description' =>
        'Il pasticcio di pollo e patate è una corroborante pietanza di origine anglosassone, tipica delle giornate uggiose e piovose che ricorda il pasticcio del pastore francese. Un delicato guscio di patate che al suo interno racchiude un gustoso stufato di pollo e funghi profumato alla birra.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello tonnato',
        'description' =>
        'Il vitello tonnato è uno dei secondi piatti freddi più classici della tradizione culinaria italiana. Secondo la tradizione consolidata la ricetta nasce a Cuneo intorno al 1700, ma molti ne fanno risalire le origini a Lombardia, Veneto ed Emilia Romagna.',
        'ingredients' => '800 gr di girello o magatello di vitella, 1 bicchiere di vino bianco, 1 dado da brodo, 1 bicchiere di acquaolio extravergine, 1 carota, 1 cipolla, 100 gr di tonno, 3 uova, 1 cucchiaio di capperi, 6 acciughe sott’olio',
        'price' => 17.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai peperoni',
        'description' =>
        'Il pollo ai peperoni è una ricetta tipica del ferragosto romano, ma che viene preparata molto comunemente anche nel resto d’Italia.',
        'ingredients' => '1.2 kg di pollo, peperone giallo grande, peperone rosso grande, cipolla bianca piccola, vino bianco, aglio, olive verdi grandi, brodo vegetale, maggiorana fresca, olio extravergine di oliva sale, pepe',
        'price' => 13.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Polpette al forno con patate',
        'description' =>
        'Le polpette al forno con patate rappresentano la soluzione perfetta per una cena in famiglia: la ricetta facile e veloce.',
        'ingredients' => '',
        'price' => 7.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo al curry',
        'description' =>
        'Il pollo al curry è un piatto di origine indiana che si prepara in pochissimo tempo ed è adatto a tutta la famiglia. Il gusto e il livello di speziatura di questo piatto varieranno a seconda del tipo di curry in polvere che userete, quindi aggiustate il condimento secondo i vostri gusti assaggiando e regolando di conseguenza le dosi.',
        'ingredients' => '',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Brasciole pugliesi al sugo',
        'description' =>
        'Le brasciole al sugo sono uno dei piatti più famosi della tradizione culinaria pugliese. Sono degli di involtini di cavallo o di carne di manzo con un ripieno insaporito da prezzemolo, aglio e pecorino.',
        'ingredients' => 'Scamone di manzo a fette, cipolla piccola, pecorino grattugiato, aglio, prezzemolo tritato, passata di pomodoro, ,vino, acqua, sale, pepe, olio extravergine di oliva',
        'price' => 18.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello alle arance ',
        'description' =>
        'Carne alla brace',
        'ingredients' => '700 g di arrosto di vitello, 2 arance non trattate, 1 dl di vino bianco, 1/2 dl di brandy, 30 g di burro, 1 foglia di alloro, sale, pepe.',
        'price' => 28.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Costolette di castrato',
        'description' =>
        'Carne cotta alla brace',
        'ingredients' => '700 g di costolette di castrato, cipolla, carota, 3 pomodori, prezzemolo, 1/2 bicchiere di vino rosso, olio, burro.',
        'price' => 22.3,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Involtini di petto di pollo con speck e provola',
        'description' => 'Gli involtini di petto di pollo con speck e provola sono un gustosissimo secondo piatto a base di pollo.',
        'ingredients' => '300 gr di petto di pollo tagliato in 4 fettine, 100 gr di speck, 60 gr di provola silana o scamorza bianca, 200 ml di vino bianco secco, 1 cucchiaio di olio extravergine di olivamirto (qualche fogliolina) sale e pepe ',
        'price' => 13.4,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cotoletta alla milanese',
        'description' =>
        'La cotoletta alla milanese è il piatto più famoso e tipico di Milano insieme al risotto alla milanese e al panettone. La cotoletta fritta è presente anche in altre cucine tipiche come quella austriaca dove prende il nome di Wiener Schnitzel o in quella giapponese dove viene chiamata tonkatsu',
        'ingredients' => '4 fette di carne di vitella (costoletta con osso), 2 uova, pangrattato, farina, sale, 300 gr di burro chiarificato',
        'price' => 12.7,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pasticcio di pollo e patate',
        'description' =>
        'Il pasticcio di pollo e patate è una corroborante pietanza di origine anglosassone, tipica delle giornate uggiose e piovose che ricorda il pasticcio del pastore francese. Un delicato guscio di patate che al suo interno racchiude un gustoso stufato di pollo e funghi profumato alla birra.',
        'ingredients' => '',
        'price' => 15.6,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello tonnato',
        'description' =>
        'Il vitello tonnato è uno dei secondi piatti freddi più classici della tradizione culinaria italiana. Secondo la tradizione consolidata la ricetta nasce a Cuneo intorno al 1700, ma molti ne fanno risalire le origini a Lombardia, Veneto ed Emilia Romagna.',
        'ingredients' => '800 gr di girello o magatello di vitella, 1 bicchiere di vino bianco, 1 dado da brodo, 1 bicchiere di acquaolio extravergine, 1 carota, 1 cipolla, 100 gr di tonno, 3 uova, 1 cucchiaio di capperi, 6 acciughe sott’olio',
        'price' => 19.2,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai peperoni',
        'description' =>
        'Il pollo ai peperoni è una ricetta tipica del ferragosto romano, ma che viene preparata molto comunemente anche nel resto d’Italia.',
        'ingredients' => '1.2 kg di pollo, peperone giallo grande, peperone rosso grande, cipolla bianca piccola, vino bianco, aglio, olive verdi grandi, brodo vegetale, maggiorana fresca, olio extravergine di oliva sale, pepe',
        'price' => 11.2,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Polpette al forno con patate',
        'description' =>
        'Le polpette al forno con patate rappresentano la soluzione perfetta per una cena in famiglia: la ricetta facile e veloce.',
        'ingredients' => '',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo al curry',
        'description' =>
        'Il pollo al curry è un piatto di origine indiana che si prepara in pochissimo tempo ed è adatto a tutta la famiglia. Il gusto e il livello di speziatura di questo piatto varieranno a seconda del tipo di curry in polvere che userete, quindi aggiustate il condimento secondo i vostri gusti assaggiando e regolando di conseguenza le dosi.',
        'ingredients' => '',
        'price' => 12.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Braciole pugliesi al sugo',
        'description' =>
        'Le braciole al sugo sono uno dei piatti più famosi della tradizione culinaria pugliese. Sono degli di involtini di cavallo o di carne di manzo con un ripieno insaporito da prezzemolo, aglio e pecorino.',
        'ingredients' => 'Scamone di manzo a fette, cipolla piccola, pecorino grattugiato, aglio, prezzemolo tritato, passata di pomodoro, ,vino, acqua, sale, pepe, olio extravergine di oliva',
        'price' => 17.1,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste e Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 6.2,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste e Carne',
        'description' => '',
        'ingredients' => '',
        'price' => 6.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Frutti di Mare e Verdure',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Fettuccine di Riso Saltate con Verdure Miste e Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Riso con Pollo al Curry',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Soia con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Soia con Frutti di Mare',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Gnocchi di Riso con Verdure',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso alla Cantonese',
        'description' => '',
        'ingredients' => '',
        'price' => 3.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso Con Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso Piccante al Maialino',
        'description' => '',
        'ingredients' => '',
        'price' => 3.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Manzo',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Frutti di Mare e Pomodoro',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso alla Piastra',
        'description' => 'in salsa satè con frutti di mare',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Pollo in Salsa Limone',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo in Salsa Piccante',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo in Nido di Rondine',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai Peperoni',
        'description' => '',
        'ingredients' => '',
        'price' => 4.9,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Ravioli alla Griglia',
        'description' => 'carne macinata, cipolline e verza',
        'ingredients' => '',
        'price' => 4.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Ravioli Xiaomai di Gamberi',
        'description' => 'gamberi e carne macinata',
        'ingredients' => '',
        'price' => 3.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Involtini Primavera',
        'description' => 'farina, verza e carote',
        'ingredients' => '',
        'price' => 1.7,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Cornetto Nutella',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Cornetto Frutti di Bosco',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Cornetto Marmellata di Ciliegie',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Waffle con Sciroppo di Acero',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Sciroppo di Acero',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crepes Marmellata di Limone',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Cioccolato Bianco e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Cioccolato Fondente e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Nutella e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Nutella e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Cioccolato Bianco e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Galak',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Kinder Maxi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Kinder Cereali',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Twix',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Snickers',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Mascarpone',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Classic Burger',
        'description' => '200g hamburger, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cheeseburger',
        'description' => '200g hamburger, formaggio cheddar, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Bacon Cheeseburger',
        'description' => '200g hamburger, bacon, formaggio cheddar, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Hamburger Bismarck',
        'description' => '200g hamburger, bacon, formaggio cheddar, uovo all’occhio di bue, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Doppio Cheeseburger',
        'description' => '2 hamburger da 200g, doppio formaggio cheddar, maionese al cetriolo, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 13.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Hamburger Red Hot',
        'description' => '200g hamburger, pecorino semistagionato di pienza, ‘nduja artigianale di spilinga, lattuga e pomodoro',
        'ingredients' => '',
        'price' => 14.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Project Burger',
        'description' => 'hamburger, Parmigiano Reggiano, lattuga, curry mudras e cipolla saltata',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Truffle Burger',
        'description' => 'hamburger, caciocavallo al tartufo bianco, bacon, rucola e lattuga',
        'ingredients' => '',
        'price' => 15.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Norvegese',
        'description' => 'panino con rosti di patate, salmone norvegese affumicato, lattuga, pomodoro e salsa tzatziki',
        'ingredients' => '',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Margherita',
        'description' =>
        'La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella (tradizionalmente è usato il fior di latte, non quella di bufala), basilico fresco, sale e olio; è, assieme alla pizza marinara, la più popolare pizza italiana.',
        'ingredients' => 'pomodoro, mozzarella',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Diavola',
        'description' =>
        'Tipica in diverse cucine regionali italiane, è divenuta famosa come specialità della cucina napoletana. La città di Napoli ha svolto infatti un ruolo importantissimo nella storia della pizza, creando ed esportando questa specialità che è ora la più diffusa nel mondo',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Spaghetti alla Carbonara',
        'description' =>
        'La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso',
        'ingredients' => '',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti Cacio e Pepe',
        'description' =>
        'Il cacio e pepe è un piatto caratteristico del Lazio. Come suggerisce il nome, gli ingredienti sono molto semplici e includono solo pepe nero, formaggio pecorino romano e pasta',
        'ingredients' => 'spaghetti, pepe, pecorino',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso al Pomodoro',
        'description' =>
        '',
        'ingredients' => 'riso, pomodoro, olio',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti al pomodoro',
        'description' =>
        'La nostra specialità, con ingredienti coltivati a km 0.',
        'ingredients' => 'spaghetti, pomodoro, aglio, olio',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Paccheri alla Norma',
        'description' =>
        'Pasta con melanzane, pomodori e ricotta.',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Maialona',
        'description' =>
        'Pizza con salsiccia, salamino, wurstel e prosciutto cotto',
        'ingredients' => '',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Peposo',
        'description' =>
        'Il peposo è una ricetta toscana, tipica dell\'Impruneta, un paesino alle porte di Firenze. Simile ad uno spezzatino, ma con molte sfaccettature diverse. La carne è cotta nel vino, solitamente si utilizza il Chianti, il vino rosso tipico di questa terra molto corposo.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Lampredotto',
        'description' =>
        'Simile alla trippa, si serve in un morbido panino con salsa verde o anche solo con sale, olio e un pizzico di piccante per chi lo gradisce.',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Spaghetti Cacio e Pepe',
        'description' =>
        'Piatto caratteristico del Lazip, dagli ingredienti semplici e genuini.',
        'ingredients' => 'spaghetti, cacio, pepe, olio',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Marinara',
        'description' =>
        '',
        'ingredients' => 'pomodoro, aglio, pomodoro, origano',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Zenith',
        'description' =>
        'La nostra specialità!',
        'ingredients' => 'pomodoro, burrata, salamino piccante',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Marinara',
        'description' =>
        '',
        'ingredients' => 'pomodoro, aglio, pomodoro, origano',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Ramen',
        'description' =>
        'Il ramen è un piatto giapponese, costituito da noodles di grano serviti in un brodo di carne o, talvolta, di pesce, spesso aromatizzato con salsa di soia, miso o shio.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Dorayaki',
        'description' => 'Il dorayaki è un tipo di dolce giapponese composto da due pancake, formati a partire dalla kasutera (un impasto simile al pan di spagna), e riempito al centro con l\'anko, una salsa dolce rossastra ricavata dai fagioli azuki.',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Zuppa di Miso',
        'description' => '',
        'ingredients' => 'Acqua, carote, daikon, porri, olio, tofu, miso, zenzero, wakame, sale',
        'price' => 7.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Onigiri',
        'description' => 'Le tipiche polpette del continente del Sol Levante.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Onigiri',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => false,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Onigiri',
        'description' => '',
        'ingredients' => '',
        'price' => 5.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => 'Il tempura è un piatto della cucina giapponese a base di verdure e/o pesce, impastellati separatamente e fritti.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => 'La tempura è un piatto proveniente dalla cucina giapponese. Si tratta di una particolare frittura a base di pesce e verdure, che ha il pregio di essere molto croccante e saporita.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Ramen',
        'description' =>
        'Il ramen è un piatto giapponese, costituito da noodles di grano serviti in un brodo di carne o, talvolta, di pesce, spesso aromatizzato con salsa di soia, miso o shio.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Dorayaki',
        'description' => 'Il dorayaki è un tipo di dolce giapponese composto da due pancake, formati a partire dalla kasutera (un impasto simile al pan di spagna), e riempito al centro con l\'anko, una salsa dolce rossastra ricavata dai fagioli azuki.',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Zuppa di Miso',
        'description' => '',
        'ingredients' => 'Acqua, carote, daikon, porri, olio, tofu, miso, zenzero, wakame, sale',
        'price' => 7.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Onigiri',
        'description' => 'Le tipiche polpette del continente del Sol Levante.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Udon',
        'description' => 'I tipici spaghetti giapponesi!',
        'ingredients' => '',
        'price' => 7.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Onigiri',
        'description' => '',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => false,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => 'Il tempura è un piatto della cucina giapponese a base di verdure e/o pesce, impastellati separatamente e fritti.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => false,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Samosa',
        'description' => 'Cibo di strada fritto viene riempito con patate o carne, e altri accompagnamenti come i piselli e servito con una salsa di chutney come intingolo.',
        'ingredients' => 'patate, carne, verdure miste',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Thali',
        'description' => 'È il nome di un piatto rotondo e si riferisce anche al pasto di per sé che comprende molti piccoli assaggi prelibati, ognuno contenuto in una ciotola servita a sua volta su un piatto. ',
        'ingredients' => '',
        'price' => 14.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Naan all’aglio',
        'description' => 'Il naan, il tipico pane indiano, è sempre buonissimo, ma quello all’aglio è decisamente il più buono. Viene servito caldo e spalmato con un delizioso condimento all’aglio (con veri e propri pezzetti di aglio).',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Parantha',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Lassi',
        'description' => 'Bevanda a base di yogurt è disponibile in una vasta gamma di gusti, dall’acqua di rose al mango allo zafferano',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Bevanda',
    ],
    [
        'name' => 'Samosa',
        'description' => 'Cibo di strada fritto viene riempito con patate o carne, e altri accompagnamenti come i piselli e servito con una salsa di chutney come intingolo.',
        'ingredients' => 'patate, carne, verdure miste',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Thali',
        'description' => 'È il nome di un piatto rotondo e si riferisce anche al pasto di per sé che comprende molti piccoli assaggi prelibati, ognuno contenuto in una ciotola servita a sua volta su un piatto. ',
        'ingredients' => '',
        'price' => 14.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Naan all’aglio',
        'description' => 'Il naan, il tipico pane indiano, è sempre buonissimo, ma quello all’aglio è decisamente il più buono. Viene servito caldo e spalmato con un delizioso condimento all’aglio (con veri e propri pezzetti di aglio).',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Parantha',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Lassi',
        'description' => 'Bevanda a base di yogurt è disponibile in una vasta gamma di gusti, dall’acqua di rose al mango allo zafferano',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Bevanda',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Crispy McBacon',
        'description' =>
        "Un Grande Classico che non tramonterà mai. Carne 100% bovina da allevamenti italiani, croccante bacon 100% da pancetta italiana e formaggio, accompagnati dall'inconfondibile salsa Crispy. Non serve altro per incoronare Crispy McBacon® re della croccantezza e del gusto.",
        'ingredients' => '',
        'price' => 4.74,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Bacon King 3.0 Rodeo',
        'description' =>
        "Bacon King 3.0 Rodeo: 3 strati di carne alla griglia, 3 strati di formaggio, 8 fette di delizioso bacon, ketchup, maionese e 6 anelli di cipolla croccanti. Vieni a provarlo in tutta la sua abbondanza.",
        'ingredients' => '',
        'price' => 12.35,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'King Burger Napulè',
        'description' => "",
        'ingredients' => 'Salsiccia, Friarelli, Mozzarella di Bufala, Provola Affumicata',
        'price' => 7.50,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Chicken Burger',
        'description' => "Petto di pollo tagliato a mano con panatura ai cinque cereali, lattuga, scamorza affumicata, peperoni, maionese al pomodoro homemade",
        'ingredients' => '',
        'price' => 9.50,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Spaghetti alla Carbonara',
        'description' =>
        'La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso',
        'ingredients' => [
            'spaghetti',
            'guanciale',
            'uova',
            'pecorino',
            'pepe',
        ],
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Spaghetti Cacio e Pepe',
        'description' =>
        'Il cacio e pepe è un piatto caratteristico del Lazio. Come suggerisce il nome, gli ingredienti sono molto semplici e includono solo pepe nero, formaggio pecorino romano e pasta',
        'ingredients' => ['spaghetti', 'pepe', 'pecorino'],
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Spaghetti allo Scoglio',
        'description' =>
        'Gli spaghetti allo scoglio sono un primo piatto di mare profumato e gustoso che racchiude i veri sapori e aromi del mediterraneo.',
        'ingredients' => [
            'Spaghetti',
            'Cozze',
            'Vongole',
            'Calamari',
            'Scampi',
            'Pomodorini ciliegino',
            "Olio extravergine d'oliva",
            'Aglio',
            'Prezzemolo',
            'Vino bianco',
            'Pepe nero',
        ],
        'price' => 15.0,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Ravioli Ricotta e Spinaci',
        'description' =>
        "I ravioli ricotta e spinaci sono una delle preparazioni più conosciute a base di pasta fresca all'uovo, perfetti per feste e giorni di magro!",
        'ingredients' => [
            'Uova',
            'Semola',
            'Spinaci',
            'Ricotta Vaccina',
            'Parmigiano Reggiano DOP',
            'Noce moscata',
            'Pepe nero'
        ],
        'price' => 12.0,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Margherita',
        'description' =>
        'La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella (tradizionalmente è usato il fior di latte, non quella di bufala), basilico fresco, sale e olio; è, assieme alla pizza marinara, la più popolare pizza italiana.',
        'ingredients' => ['pomodoro', 'mozzarella'],
        'price' => 6.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Diavola',
        'description' =>
        'Tipica in diverse cucine regionali italiane, è divenuta famosa come specialità della cucina napoletana. La città di Napoli ha svolto infatti un ruolo importantissimo nella storia della pizza, creando ed esportando questa specialità che è ora la più diffusa nel mondo',
        'ingredients' => [
            'pomodoro',
            'mozzarella',
            'salame piccante',
            'origano',
        ],
        'price' => 8.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Boscaiola',
        'description' =>
        'La pizza boscaiola è davvero gustosa caratterizzata da funghi champignon accompagnati da gustosi pezzetti di salsiccia e ricoperta infine da mozzarella.',
        'ingredients' => [
            'funghi champignon',
            'salsiccia',
            'mozzarella',
        ],
        'price' => 9.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Napoli',
        'description' =>
        'La pizza Napoli viene realizzata stendendo la pasta per la pizza, aggiungendo il pomodoro, i capperi ed i filetti di acciughe cuocendo infine la pizza in forno.',
        'ingredients' => [
            'pomodoro',
            'acciughe',
            'pepe',
            'capperi',
        ],
        'price' => 7.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Poke Bowl',
        'description' => "La Poke Bowl Hawaii è un cibo hawaiano, un piatto unico fresco e genuino, che, con gli anni, ha conquistato tutti ed è diventato simbolo di cucina salutista e di cibo healty.",
        'ingredients' => [
            'riso',
            'salmone affumicato',
            'ravanelli',
            'mango',
            'salsa di soia',
            'edamame',
            'avocado',
            'rucola',
            'semi di sesamo',
        ],
        'price' => 10.00,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Poke Tonno',
        'description' => "La Poke Bowl Hawaii è un cibo hawaiano, un piatto unico fresco e genuino, che, con gli anni, ha conquistato tutti ed è diventato simbolo di cucina salutista e di cibo healty.",
        'ingredients' => 'Ciotola di riso con tonno, insalata di alghe, edamame e avocado.',
        'price' => 11.00,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Octopus Poke',
        'description' => "Riso venere, polpo marinato, avocado, spinacino, carote, verza, edamame, salsa teriyaki, salsa mango, habanero e semi di sesamo.",
        'ingredients' => '',
        'price' => 10.50,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'Poke Tonno',
        'description' => "Riso venere, salmone crudo, avocado, edamame, germogli di soia, surimi, verza, salsa teriyaki e semi di sesamo.",
        'ingredients' => '',
        'price' => 10.50,
        'availability' => true,
        'course' => 'Primi',
    ],
    [
        'name' => 'EDAMAME',
        'description' => '',
        'ingredients' => 'Fagioli di soia giapponese',
        'price' => 4.0,
        'availability' => false,
        'course' => 'primo',
    ],
    [
        'name' => 'SAKE',
        'description' => '',
        'ingredients' => 'Nigiri di salmone',
        'price' => 2.50,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'AMAEBI',
        'description' => '',
        'ingredients' => 'Nigiri di gambero crudo',
        'price' => 3.0,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'SAKE TEMAKI',
        'description' => '',
        'ingredients' => 'Cono di alga con riso, salmone e avocado',
        'price' => 5.0,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'NEGITORO TEMAKI',
        'description' => '',
        'ingredients' => 'Cono di alga con riso, tonno, cipollotti e salsa piccante',
        'price' => 5.0,
        'availability' => false,
        'course' => 'primo',
    ],

    [
        'name' => 'TEMPURA TEMAKI',
        'description' => '',
        'ingredients' => 'Cono di alga con riso, tempura di gamberone e lattuga',
        'price' => 6.0,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'NEGITORO TEMAKI',
        'description' => '',
        'ingredients' => 'Cono di alga con riso, tonno, cipollotti e salsa piccante',
        'price' => 5.0,
        'availability' => false,
        'course' => 'primo',
    ],
    [
        'name' => 'URA PHILADELPHIA',
        'description' => '',
        'ingredients' => 'Riso, philadelphia, gamberi* cotti e avocado',
        'price' => 8.0,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'BROWN FUTOMAKI',
        'description' => '',
        'ingredients' => 'Riso, frittata, gamberi* cotti, avocado e anguilla',
        'price' => 8.0,
        'availability' => false,
        'course' => 'primo',
    ],
    [
        'name' => 'TEMPURA URAMAKI',
        'description' => '',
        'ingredients' => 'Riso, tempura di gamberoni e tobiko',
        'price' => 10.0,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'INSALATA DI FINOCCHI E ARANCE',
        'description' => '',
        'ingredients' => 'Finocchi, Arance, Pinoli, Uvetta, Sale, Olio di oliva extravergine di oliva, Aceto di mele, Semi di zucca',
        'price' => 9.0,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA DI POLLO SAPORITA',
        'description' => 'Fresca, genuina e colorata! La nostra insalata di pollo saporita è una carica di energia',
        'ingredients' => 'Petto di pollo in filetti, Olive verdi denocciolate, Cetriolini sottaceto, Peperoni rossi, Sedano bianco, Carote, Groviera, Sale fino ',
        'price' => 8.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA DI PUNTARELLE ALLA ROMANA',
        'description' => 'L’insalata di puntarelle alla romana è un contorno semplice e gustoso tipico del Lazio che vengono servite con una gustosa salsa di condimento.',
        'ingredients' => 'Puntarelle germogli di cicoria catalogna, Acciughe alici filetti sott\'olio, Olio extravergine d\'oliva, Aceto di vino bianco, Aglio, Sale fino, Pepe nero',
        'price' => 7.50,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'CAESAR SALAD',
        'description' => 'La Caesar salad è un piatto celebre creato dallo chef italiano Cesare Cardini, che emigrato negli Stati Uniti si inventò quest\'irresistibile insalata!',
        'ingredients' => 'Lattuga romana, Pane casereccio, Parmigiano Reggiano DOP, Aglio, Worcestershire sauce, Uova, Sale fino, Olio extravergine d\'oliva aromatizzato all\'aglio, Pepe nero, Olio extravergine d\'oliva, Aceto di vino bianco, Succo di limone',
        'price' => 6.50,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA DI CARCIOFI',
        'description' => 'L\'insalata di carciofi è un contorno primaverile condito con una citronette, perfetto da accompagnare a secondi piatti di carne o di pesce.',
        'ingredients' => 'Carciofi, Grana Padano DOP, Limone',
        'price' => 4.0,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA PANTESCA',
        'description' => 'L\'insalata pantesca è una ricetta tipica dell\'isola di Pantelleria, un\'insalata mista di patate e pomodori arricchita con capperi, olive e cipolle!',
        'ingredients' => 'Grana Padano DOP, Limone, Capperi, Cipolle, Pomodori',
        'price' => 9.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA DI ARANCE',
        'description' => 'L’insalata di arance è un contorno tipico della Sicilia, fresco e gustoso, ideale per accompagnare saporiti secondi piatti di carne o pesce.',
        'ingredients' => 'Arance tarocco, Cipolle rosse, Olive nere, Basilico, Olio extravergine d\'oliva, Pepe nero, Sale fino',
        'price' => 8.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA DI PATATE AL VERDE',
        'description' => 'L\'insalata di patate al verde è un contorno dal sapore fresco e appetitoso, una ricetta leggera per accompagnare pietanze a base di carne o pesce.',
        'ingredients' => 'Patate , Basilico fresco , Prezzemolo fresco , Capperi sott\'aceto , Acciughe (alici) sott\'olio , Olio extravergine d\'oliva , Pepe nero , Origano essiccato',
        'price' => 8.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA NIZZARDA',
        'description' => 'L\'insalata nizzarda, o salade niçoise, è un piatto fresco e colorato tipico della Costa Azzurra, con uova sode e verdure crude.',
        'ingredients' => 'Uova, Lattuga, Pomodorini ciliegino, Tonno sott\'olio, Olive nere denocciolate, Cipollotto fresco, Acciughe sott\'olio, Olio extravergine d\'oliva, Sale fino, Pepe nero',
        'price' => 9.50,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'INSALATA DI FAGIOLINI',
        'description' => 'L\'insalata di fagiolini è una ricetta fresca e sfiziosa, perfetta per affrontare il caldo estivo con gusto e senza tralasciare il gusto!',
        'ingredients' => 'Fagiolini, Pomodorini, Scalogno, Olio di semi, Zucchero integrale di canna, Acqua, Mandorle in scaglie, Feta',
        'price' => 4.0,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'CAPRESE',
        'description' => '',
        'ingredients' => 'Mozzarella, pomodoro maturi, olio extravergine d\'oliva, basilico, sale',
        'price' => 3.50,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'PENNE ALLA MEDITERRANEA',
        'description' => 'La pasta alla mediterranea è un primo piatto semplice e saporito che racchiude in sé tutti i gusti e i sapori delle verdure e delle erbe mediterranee.',
        'ingredients' => 'Certosa, pomodori freschi, olive nere snocciolate, olive verdi snocciolate, capperi, peperoni sottaceto agrodolci, basilico, erba cipollina
olio extra vergine d\'oliva
sale e pepe, aglio',
        'price' => 8.0,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'PESCE SPADA ALLA PIZZAIOLA',
        'description' => '',
        'ingredients' => 'tranci di pesce spada, Mozzarella, pomodorini, aglio, capperi, olive nere',
        'price' => 4.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'CREPES MEDITERRANEA',
        'description' => '',
        'ingredients' => 'melanzana, Mozzarella, capperi, olive, pomodoro',
        'price' => 7.50,
        'availability' => true,
        'course' => 'primo',
    ],
    [
        'name' => 'SNACK DI PARMIGIANO REGGIANO',
        'description' => '',
        'ingredients' => 'Parmigiano reggiano',
        'price' => 1.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'ARACHIDI',
        'description' => '',
        'ingredients' => 'Arachidi',
        'price' => 2.0,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'CHIPS GUSTO PIZZA',
        'description' => '',
        'ingredients' => 'Chips',
        'price' => 1.20,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'TARALLI',
        'description' => '',
        'ingredients' => 'Taralli',
        'price' => 2.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'POP CORN',
        'description' => '',
        'ingredients' => 'Pop Corn',
        'price' => 1.30,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'SNACK DI PARMIGIANO REGGIANO',
        'description' => '',
        'ingredients' => 'Parmigiano reggiano',
        'price' => 2.0,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'ARACHIDI',
        'description' => '',
        'ingredients' => 'Arachidi',
        'price' => 2.8,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'CHIPS GUSTO PIZZA',
        'description' => '',
        'ingredients' => 'Chips',
        'price' => 3.0,
        'availability' => true,
        'course' => 'secondo',
    ],
    [
        'name' => 'TARALLI',
        'description' => '',
        'ingredients' => 'Taralli',
        'price' => 1.6,
        'availability' => false,
        'course' => 'secondo',
    ],
    [
        'name' => 'POP CORN',
        'description' => '',
        'ingredients' => 'Pop Corn',
        'price' => 1.10,
        'availability' => true,
        'course' => 'secondo',
    ],
];
