<?php

return [
    [
        'name' => 'Vitello alle arance ',
        'description' =>
        'Carne alla brace',
        'ingredients' => '700 g di arrosto di vitello, 2 arance non trattate, 1 dl di vino bianco, 1/2 dl di brandy, 30 g di burro, 1 foglia di alloro, sale, pepe.',
        'price' => 22.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Costolette di castrato',
        'description' =>
        'Carne cotta alla brace',
        'ingredients' => '700 g di costolette di castrato, cipolla, carota, 3 pomodori, prezzemolo, 1/2 bicchiere di vino rosso, olio, burro.',
        'price' => 25.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Involtini di petto di pollo con speck e provola',
        'description' => 'Gli involtini di petto di pollo con speck e provola sono un gustosissimo secondo piatto a base di pollo.',
        'ingredients' => '300 gr di petto di pollo tagliato in 4 fettine, 100 gr di speck, 60 gr di provola silana o scamorza bianca, 200 ml di vino bianco secco, 1 cucchiaio di olio extravergine di olivamirto (qualche fogliolina) sale e pepe ',
        'price' => 18.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cotoletta alla milanese',
        'description' =>
        'La cotoletta alla milanese è il piatto più famoso e tipico di Milano insieme al risotto alla milanese e al panettone. La cotoletta fritta è presente anche in altre cucine tipiche come quella austriaca dove prende il nome di Wiener Schnitzel o in quella giapponese dove viene chiamata tonkatsu',
        'ingredients' => '4 fette di carne di vitella (costoletta con osso), 2 uova, pangrattato, farina, sale, 300 gr di burro chiarificato',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pasticcio di pollo e patate',
        'description' =>
        'Il pasticcio di pollo e patate è una corroborante pietanza di origine anglosassone, tipica delle giornate uggiose e piovose che ricorda il pasticcio del pastore francese. Un delicato guscio di patate che al suo interno racchiude un gustoso stufato di pollo e funghi profumato alla birra.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello tonnato',
        'description' =>
        'Il vitello tonnato è uno dei secondi piatti freddi più classici della tradizione culinaria italiana. Secondo la tradizione consolidata la ricetta nasce a Cuneo intorno al 1700, ma molti ne fanno risalire le origini a Lombardia, Veneto ed Emilia Romagna.',
        'ingredients' => '800 gr di girello o magatello di vitella, 1 bicchiere di vino bianco, 1 dado da brodo, 1 bicchiere di acquaolio extravergine, 1 carota, 1 cipolla, 100 gr di tonno, 3 uova, 1 cucchiaio di capperi, 6 acciughe sott’olio',
        'price' => 17.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai peperoni',
        'description' =>
        'Il pollo ai peperoni è una ricetta tipica del ferragosto romano, ma che viene preparata molto comunemente anche nel resto d’Italia.',
        'ingredients' => '1.2 kg di pollo, peperone giallo grande, peperone rosso grande, cipolla bianca piccola, vino bianco, aglio, olive verdi grandi, brodo vegetale, maggiorana fresca, olio extravergine di oliva sale, pepe',
        'price' => 13.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Polpette al forno con patate',
        'description' =>
        'Le polpette al forno con patate rappresentano la soluzione perfetta per una cena in famiglia: la ricetta facile e veloce.',
        'ingredients' => '',
        'price' => 7.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo al curry',
        'description' =>
        'Il pollo al curry è un piatto di origine indiana che si prepara in pochissimo tempo ed è adatto a tutta la famiglia. Il gusto e il livello di speziatura di questo piatto varieranno a seconda del tipo di curry in polvere che userete, quindi aggiustate il condimento secondo i vostri gusti assaggiando e regolando di conseguenza le dosi.',
        'ingredients' => '',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Brasciole pugliesi al sugo',
        'description' =>
        'Le brasciole al sugo sono uno dei piatti più famosi della tradizione culinaria pugliese. Sono degli di involtini di cavallo o di carne di manzo con un ripieno insaporito da prezzemolo, aglio e pecorino.',
        'ingredients' => 'Scamone di manzo a fette, cipolla piccola, pecorino grattugiato, aglio, prezzemolo tritato, passata di pomodoro, ,vino, acqua, sale, pepe, olio extravergine di oliva',
        'price' => 18.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello alle arance ',
        'description' =>
        'Carne alla brace',
        'ingredients' => '700 g di arrosto di vitello, 2 arance non trattate, 1 dl di vino bianco, 1/2 dl di brandy, 30 g di burro, 1 foglia di alloro, sale, pepe.',
        'price' => 28.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Costolette di castrato',
        'description' =>
        'Carne cotta alla brace',
        'ingredients' => '700 g di costolette di castrato, cipolla, carota, 3 pomodori, prezzemolo, 1/2 bicchiere di vino rosso, olio, burro.',
        'price' => 22.3,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Involtini di petto di pollo con speck e provola',
        'description' => 'Gli involtini di petto di pollo con speck e provola sono un gustosissimo secondo piatto a base di pollo.',
        'ingredients' => '300 gr di petto di pollo tagliato in 4 fettine, 100 gr di speck, 60 gr di provola silana o scamorza bianca, 200 ml di vino bianco secco, 1 cucchiaio di olio extravergine di olivamirto (qualche fogliolina) sale e pepe ',
        'price' => 13.4,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cotoletta alla milanese',
        'description' =>
        'La cotoletta alla milanese è il piatto più famoso e tipico di Milano insieme al risotto alla milanese e al panettone. La cotoletta fritta è presente anche in altre cucine tipiche come quella austriaca dove prende il nome di Wiener Schnitzel o in quella giapponese dove viene chiamata tonkatsu',
        'ingredients' => '4 fette di carne di vitella (costoletta con osso), 2 uova, pangrattato, farina, sale, 300 gr di burro chiarificato',
        'price' => 12.7,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pasticcio di pollo e patate',
        'description' =>
        'Il pasticcio di pollo e patate è una corroborante pietanza di origine anglosassone, tipica delle giornate uggiose e piovose che ricorda il pasticcio del pastore francese. Un delicato guscio di patate che al suo interno racchiude un gustoso stufato di pollo e funghi profumato alla birra.',
        'ingredients' => '',
        'price' => 15.6,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello tonnato',
        'description' =>
        'Il vitello tonnato è uno dei secondi piatti freddi più classici della tradizione culinaria italiana. Secondo la tradizione consolidata la ricetta nasce a Cuneo intorno al 1700, ma molti ne fanno risalire le origini a Lombardia, Veneto ed Emilia Romagna.',
        'ingredients' => '800 gr di girello o magatello di vitella, 1 bicchiere di vino bianco, 1 dado da brodo, 1 bicchiere di acquaolio extravergine, 1 carota, 1 cipolla, 100 gr di tonno, 3 uova, 1 cucchiaio di capperi, 6 acciughe sott’olio',
        'price' => 19.2,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai peperoni',
        'description' =>
        'Il pollo ai peperoni è una ricetta tipica del ferragosto romano, ma che viene preparata molto comunemente anche nel resto d’Italia.',
        'ingredients' => '1.2 kg di pollo, peperone giallo grande, peperone rosso grande, cipolla bianca piccola, vino bianco, aglio, olive verdi grandi, brodo vegetale, maggiorana fresca, olio extravergine di oliva sale, pepe',
        'price' => 11.2,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Polpette al forno con patate',
        'description' =>
        'Le polpette al forno con patate rappresentano la soluzione perfetta per una cena in famiglia: la ricetta facile e veloce.',
        'ingredients' => '',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo al curry',
        'description' =>
        'Il pollo al curry è un piatto di origine indiana che si prepara in pochissimo tempo ed è adatto a tutta la famiglia. Il gusto e il livello di speziatura di questo piatto varieranno a seconda del tipo di curry in polvere che userete, quindi aggiustate il condimento secondo i vostri gusti assaggiando e regolando di conseguenza le dosi.',
        'ingredients' => '',
        'price' => 12.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Brasciole pugliesi al sugo',
        'description' =>
        'Le brasciole al sugo sono uno dei piatti più famosi della tradizione culinaria pugliese. Sono degli di involtini di cavallo o di carne di manzo con un ripieno insaporito da prezzemolo, aglio e pecorino.',
        'ingredients' => 'Scamone di manzo a fette, cipolla piccola, pecorino grattugiato, aglio, prezzemolo tritato, passata di pomodoro, ,vino, acqua, sale, pepe, olio extravergine di oliva',
        'price' => 17.1,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste e Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 6.2,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste e Carne',
        'description' => '',
        'ingredients' => '',
        'price' => 6.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Frutti di Mare e Verdure',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Fettuccine di Riso Saltate con Verdure Miste e Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Riso con Pollo al Curry',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Soia con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Soia con Frutti di Mare',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Gnocchi di Riso con Verdure',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso alla Cantonese',
        'description' => '',
        'ingredients' => '',
        'price' => 3.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso Con Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso Piccante al Maialino',
        'description' => '',
        'ingredients' => '',
        'price' => 3.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Manzo',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Frutti di Mare e Pomodoro',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso alla Piastra',
        'description' => 'in salsa satè con frutti di mare',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Pollo in Salsa Limone',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo in Salsa Piccante',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo in Nido di Rondine',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai Peperoni',
        'description' => '',
        'ingredients' => '',
        'price' => 4.9,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Ravioli alla Griglia',
        'description' => 'carne macinata, cipolline e verza',
        'ingredients' => '',
        'price' => 4.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Ravioli Xiaomai di Gamberi',
        'description' => 'gamberi e carne macinata',
        'ingredients' => '',
        'price' => 3.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Involtini Primavera',
        'description' => 'farina, verza e carote',
        'ingredients' => '',
        'price' => 1.7,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Cornetto Nutella',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Cornetto Frutti di Bosco',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Cornetto Marmellata di Ciliegie',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Waffle con Sciroppo di Acero',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Sciroppo di Acero',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crepes Marmellata di Limone',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Cioccolato Bianco e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Cioccolato Fondente e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Nutella e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Nutella e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Cioccolato Bianco e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Galak',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Kinder Maxi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Kinder Cereali',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Twix',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Snickers',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Mascarpone',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Classic Burger',
        'description' => '200g hamburger, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cheeseburger',
        'description' => '200g hamburger, formaggio cheddar, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Bacon Cheeseburger',
        'description' => '200g hamburger, bacon, formaggio cheddar, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Hamburger Bismarck',
        'description' => '200g hamburger, bacon, formaggio cheddar, uovo all’occhio di bue, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Doppio Cheeseburger',
        'description' => '2 hamburger da 200g, doppio formaggio cheddar, maionese al cetriolo, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 13.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Hamburger Red Hot',
        'description' => '200g hamburger, pecorino semistagionato di pienza, ‘nduja artigianale di spilinga, lattuga e pomodoro',
        'ingredients' => '',
        'price' => 14.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Project Burger',
        'description' => 'hamburger, Parmigiano Reggiano, lattuga, curry mudras e cipolla saltata',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Truffle Burger',
        'description' => 'hamburger, caciocavallo al tartufo bianco, bacon, rucola e lattuga',
        'ingredients' => '',
        'price' => 15.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Norvegese',
        'description' => 'panino con rosti di patate, salmone norvegese affumicato, lattuga, pomodoro e salsa tzatziki',
        'ingredients' => '',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Margherita',
        'description' =>
        'La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella (tradizionalmente è usato il fior di latte, non quella di bufala), basilico fresco, sale e olio; è, assieme alla pizza marinara, la più popolare pizza italiana.',
        'ingredients' => 'pomodoro, mozzarella',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Diavola',
        'description' =>
        'Tipica in diverse cucine regionali italiane, è divenuta famosa come specialità della cucina napoletana. La città di Napoli ha svolto infatti un ruolo importantissimo nella storia della pizza, creando ed esportando questa specialità che è ora la più diffusa nel mondo',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Spaghetti alla Carbonara',
        'description' =>
        'La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso',
        'ingredients' => '',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti Cacio e Pepe',
        'description' =>
        'Il cacio e pepe è un piatto caratteristico del Lazio. Come suggerisce il nome, gli ingredienti sono molto semplici e includono solo pepe nero, formaggio pecorino romano e pasta',
        'ingredients' => 'spaghetti, pepe, pecorino',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso al Pomodoro',
        'description' =>
        '',
        'ingredients' => 'riso, pomodoro, olio',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti al pomodoro',
        'description' =>
        'La nostra specialità, con ingredienti coltivati a km 0.',
        'ingredients' => 'spaghetti, pomodoro, aglio, olio',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Paccheri alla Norma',
        'description' =>
        'Pasta con melanzane, pomodori e ricotta.',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Maialona',
        'description' =>
        'Pizza con salsiccia, salamino, wurstel e prosciutto cotto',
        'ingredients' => '',
        'price' => 10.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Peposo',
        'description' =>
        'Il peposo è una ricetta toscana, tipica dell\'Impruneta, un paesino alle porte di Firenze. Simile ad uno spezzatino, ma con molte sfaccettature diverse. La carne è cotta nel vino, solitamente si utilizza il Chianti, il vino rosso tipico di questa terra molto corposo.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Lampredotto',
        'description' =>
        'Simile alla trippa, si serve in un morbido panino con salsa verde o anche solo con sale, olio e un pizzico di piccante per chi lo gradisce.',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Spaghetti Cacio e Pepe',
        'description' =>
        'Piatto caratteristico del Lazip, dagli ingredienti semplici e genuini.',
        'ingredients' => 'spaghetti, cacio, pepe, olio',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Marinara',
        'description' =>
        '',
        'ingredients' => 'pomodoro, aglio, pomodoro, origano',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Zenith',
        'description' =>
        'La nostra specialità!',
        'ingredients' => 'pomodoro, burrata, salamino piccante',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Marinara',
        'description' =>
        '',
        'ingredients' => 'pomodoro, aglio, pomodoro, origano',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Pizza',
    ],
    [
        'name' => 'Ramen',
        'description' =>
        'Il ramen è un piatto giapponese, costituito da noodles di grano serviti in un brodo di carne o, talvolta, di pesce, spesso aromatizzato con salsa di soia, miso o shio.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Dorayaki',
        'description' => 'Il dorayaki è un tipo di dolce giapponese composto da due pancake, formati a partire dalla kasutera (un impasto simile al pan di spagna), e riempito al centro con l\'anko, una salsa dolce rossastra ricavata dai fagioli azuki.',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Zuppa di Miso',
        'description' => '',
        'ingredients' => 'Acqua, carote, daikon, porri, olio, tofu, miso, zenzero, wakame, sale',
        'price' => 7.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Onigiri',
        'description' => 'Le tipiche polpette del continente del Sol Levante.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Onigiri',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => false,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Onigiri',
        'description' => '',
        'ingredients' => '',
        'price' => 5.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => 'Il tempura è un piatto della cucina giapponese a base di verdure e/o pesce, impastellati separatamente e fritti.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => 'La tempura è un piatto proveniente dalla cucina giapponese. Si tratta di una particolare frittura a base di pesce e verdure, che ha il pregio di essere molto croccante e saporita.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Ramen',
        'description' =>
        'Il ramen è un piatto giapponese, costituito da noodles di grano serviti in un brodo di carne o, talvolta, di pesce, spesso aromatizzato con salsa di soia, miso o shio.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Dorayaki',
        'description' => 'Il dorayaki è un tipo di dolce giapponese composto da due pancake, formati a partire dalla kasutera (un impasto simile al pan di spagna), e riempito al centro con l\'anko, una salsa dolce rossastra ricavata dai fagioli azuki.',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Zuppa di Miso',
        'description' => '',
        'ingredients' => 'Acqua, carote, daikon, porri, olio, tofu, miso, zenzero, wakame, sale',
        'price' => 7.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Onigiri',
        'description' => 'Le tipiche polpette del continente del Sol Levante.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Udon',
        'description' => 'I tipici spaghetti giapponesi!',
        'ingredients' => '',
        'price' => 7.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Onigiri',
        'description' => '',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => false,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => 'Il tempura è un piatto della cucina giapponese a base di verdure e/o pesce, impastellati separatamente e fritti.',
        'ingredients' => '',
        'price' => 6.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Tempura',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => false,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Samosa',
        'description' => 'Cibo di strada fritto viene riempito con patate o carne, e altri accompagnamenti come i piselli e servito con una salsa di chutney come intingolo.',
        'ingredients' => 'patate, carne, verdure miste',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Thali',
        'description' => 'È il nome di un piatto rotondo e si riferisce anche al pasto di per sé che comprende molti piccoli assaggi prelibati, ognuno contenuto in una ciotola servita a sua volta su un piatto. ',
        'ingredients' => '',
        'price' => 14.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Naan all’aglio',
        'description' => 'Il naan, il tipico pane indiano, è sempre buonissimo, ma quello all’aglio è decisamente il più buono. Viene servito caldo e spalmato con un delizioso condimento all’aglio (con veri e propri pezzetti di aglio).',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Parantha',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Lassi',
        'description' => 'Bevanda a base di yogurt è disponibile in una vasta gamma di gusti, dall’acqua di rose al mango allo zafferano',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Bevanda',
    ],
    [
        'name' => 'Samosa',
        'description' => 'Cibo di strada fritto viene riempito con patate o carne, e altri accompagnamenti come i piselli e servito con una salsa di chutney come intingolo.',
        'ingredients' => 'patate, carne, verdure miste',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Thali',
        'description' => 'È il nome di un piatto rotondo e si riferisce anche al pasto di per sé che comprende molti piccoli assaggi prelibati, ognuno contenuto in una ciotola servita a sua volta su un piatto. ',
        'ingredients' => '',
        'price' => 14.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Naan all’aglio',
        'description' => 'Il naan, il tipico pane indiano, è sempre buonissimo, ma quello all’aglio è decisamente il più buono. Viene servito caldo e spalmato con un delizioso condimento all’aglio (con veri e propri pezzetti di aglio).',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => false,
        'course' => 'Primo',
    ],
    [
        'name' => 'Parantha',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Lassi',
        'description' => 'Bevanda a base di yogurt è disponibile in una vasta gamma di gusti, dall’acqua di rose al mango allo zafferano',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Bevanda',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Kebab',
        'description' => '',
        'ingredients' => 'carne di pollo e/o manzo, verdure miste, salse',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'carne di pollo e/o manzo, verdure miste, salse',
        'ingredients' => '',
        'price' => 6.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
];
