<?php

return [
    [
        'name' => 'Vitello alle arance ',
        'description' =>
        'Carne alla brace',
        'ingredients' => '700 g di arrosto di vitello, 2 arance non trattate, 1 dl di vino bianco, 1/2 dl di brandy, 30 g di burro, 1 foglia di alloro, sale, pepe.',
        'price' => 22.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Costolette di castrato',
        'description' =>
        'Carne cotta alla brace',
        'ingredients' => '700 g di costolette di castrato, cipolla, carota, 3 pomodori, prezzemolo, 1/2 bicchiere di vino rosso, olio, burro.',
        'price' => 25.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Involtini di petto di pollo con speck e provola',
        'description' => 'Gli involtini di petto di pollo con speck e provola sono un gustosissimo secondo piatto a base di pollo.',
        'ingredients' => '300 gr di petto di pollo tagliato in 4 fettine, 100 gr di speck, 60 gr di provola silana o scamorza bianca, 200 ml di vino bianco secco, 1 cucchiaio di olio extravergine di olivamirto (qualche fogliolina) sale e pepe ',
        'price' => 18.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cotoletta alla milanese',
        'description' =>
        'La cotoletta alla milanese è il piatto più famoso e tipico di Milano insieme al risotto alla milanese e al panettone. La cotoletta fritta è presente anche in altre cucine tipiche come quella austriaca dove prende il nome di Wiener Schnitzel o in quella giapponese dove viene chiamata tonkatsu',
        'ingredients' => '4 fette di carne di vitella (costoletta con osso), 2 uova, pangrattato, farina, sale, 300 gr di burro chiarificato',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pasticcio di pollo e patate',
        'description' =>
        'Il pasticcio di pollo e patate è una corroborante pietanza di origine anglosassone, tipica delle giornate uggiose e piovose che ricorda il pasticcio del pastore francese. Un delicato guscio di patate che al suo interno racchiude un gustoso stufato di pollo e funghi profumato alla birra.',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello tonnato',
        'description' =>
        'Il vitello tonnato è uno dei secondi piatti freddi più classici della tradizione culinaria italiana. Secondo la tradizione consolidata la ricetta nasce a Cuneo intorno al 1700, ma molti ne fanno risalire le origini a Lombardia, Veneto ed Emilia Romagna.',
        'ingredients' => '800 gr di girello o magatello di vitella, 1 bicchiere di vino bianco, 1 dado da brodo, 1 bicchiere di acquaolio extravergine, 1 carota, 1 cipolla, 100 gr di tonno, 3 uova, 1 cucchiaio di capperi, 6 acciughe sott’olio',
        'price' => 17.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai peperoni',
        'description' =>
        'Il pollo ai peperoni è una ricetta tipica del ferragosto romano, ma che viene preparata molto comunemente anche nel resto d’Italia.',
        'ingredients' => '1.2 kg di pollo, peperone giallo grande, peperone rosso grande, cipolla bianca piccola, vino bianco, aglio, olive verdi grandi, brodo vegetale, maggiorana fresca, olio extravergine di oliva sale, pepe',
        'price' => 13.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Polpette al forno con patate',
        'description' =>
        'Le polpette al forno con patate rappresentano la soluzione perfetta per una cena in famiglia: la ricetta facile e veloce.',
        'ingredients' => '',
        'price' => 7.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo al curry',
        'description' =>
        'Il pollo al curry è un piatto di origine indiana che si prepara in pochissimo tempo ed è adatto a tutta la famiglia. Il gusto e il livello di speziatura di questo piatto varieranno a seconda del tipo di curry in polvere che userete, quindi aggiustate il condimento secondo i vostri gusti assaggiando e regolando di conseguenza le dosi.',
        'ingredients' => '',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Brasciole pugliesi al sugo',
        'description' =>
        'Le brasciole al sugo sono uno dei piatti più famosi della tradizione culinaria pugliese. Sono degli di involtini di cavallo o di carne di manzo con un ripieno insaporito da prezzemolo, aglio e pecorino.',
        'ingredients' => 'Scamone di manzo a fette, cipolla piccola, pecorino grattugiato, aglio, prezzemolo tritato, passata di pomodoro, ,vino, acqua, sale, pepe, olio extravergine di oliva',
        'price' => 18.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello alle arance ',
        'description' =>
        'Carne alla brace',
        'ingredients' => '700 g di arrosto di vitello, 2 arance non trattate, 1 dl di vino bianco, 1/2 dl di brandy, 30 g di burro, 1 foglia di alloro, sale, pepe.',
        'price' => 28.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Costolette di castrato',
        'description' =>
        'Carne cotta alla brace',
        'ingredients' => '700 g di costolette di castrato, cipolla, carota, 3 pomodori, prezzemolo, 1/2 bicchiere di vino rosso, olio, burro.',
        'price' => 22.3,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Involtini di petto di pollo con speck e provola',
        'description' => 'Gli involtini di petto di pollo con speck e provola sono un gustosissimo secondo piatto a base di pollo.',
        'ingredients' => '300 gr di petto di pollo tagliato in 4 fettine, 100 gr di speck, 60 gr di provola silana o scamorza bianca, 200 ml di vino bianco secco, 1 cucchiaio di olio extravergine di olivamirto (qualche fogliolina) sale e pepe ',
        'price' => 13.4,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cotoletta alla milanese',
        'description' =>
        'La cotoletta alla milanese è il piatto più famoso e tipico di Milano insieme al risotto alla milanese e al panettone. La cotoletta fritta è presente anche in altre cucine tipiche come quella austriaca dove prende il nome di Wiener Schnitzel o in quella giapponese dove viene chiamata tonkatsu',
        'ingredients' => '4 fette di carne di vitella (costoletta con osso), 2 uova, pangrattato, farina, sale, 300 gr di burro chiarificato',
        'price' => 12.7,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pasticcio di pollo e patate',
        'description' =>
        'Il pasticcio di pollo e patate è una corroborante pietanza di origine anglosassone, tipica delle giornate uggiose e piovose che ricorda il pasticcio del pastore francese. Un delicato guscio di patate che al suo interno racchiude un gustoso stufato di pollo e funghi profumato alla birra.',
        'ingredients' => '',
        'price' => 15.6,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Vitello tonnato',
        'description' =>
        'Il vitello tonnato è uno dei secondi piatti freddi più classici della tradizione culinaria italiana. Secondo la tradizione consolidata la ricetta nasce a Cuneo intorno al 1700, ma molti ne fanno risalire le origini a Lombardia, Veneto ed Emilia Romagna.',
        'ingredients' => '800 gr di girello o magatello di vitella, 1 bicchiere di vino bianco, 1 dado da brodo, 1 bicchiere di acquaolio extravergine, 1 carota, 1 cipolla, 100 gr di tonno, 3 uova, 1 cucchiaio di capperi, 6 acciughe sott’olio',
        'price' => 19.2,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai peperoni',
        'description' =>
        'Il pollo ai peperoni è una ricetta tipica del ferragosto romano, ma che viene preparata molto comunemente anche nel resto d’Italia.',
        'ingredients' => '1.2 kg di pollo, peperone giallo grande, peperone rosso grande, cipolla bianca piccola, vino bianco, aglio, olive verdi grandi, brodo vegetale, maggiorana fresca, olio extravergine di oliva sale, pepe',
        'price' => 11.2,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Polpette al forno con patate',
        'description' =>
        'Le polpette al forno con patate rappresentano la soluzione perfetta per una cena in famiglia: la ricetta facile e veloce.',
        'ingredients' => '',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo al curry',
        'description' =>
        'Il pollo al curry è un piatto di origine indiana che si prepara in pochissimo tempo ed è adatto a tutta la famiglia. Il gusto e il livello di speziatura di questo piatto varieranno a seconda del tipo di curry in polvere che userete, quindi aggiustate il condimento secondo i vostri gusti assaggiando e regolando di conseguenza le dosi.',
        'ingredients' => '',
        'price' => 12.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Brasciole pugliesi al sugo',
        'description' =>
        'Le brasciole al sugo sono uno dei piatti più famosi della tradizione culinaria pugliese. Sono degli di involtini di cavallo o di carne di manzo con un ripieno insaporito da prezzemolo, aglio e pecorino.',
        'ingredients' => 'Scamone di manzo a fette, cipolla piccola, pecorino grattugiato, aglio, prezzemolo tritato, passata di pomodoro, ,vino, acqua, sale, pepe, olio extravergine di oliva',
        'price' => 17.1,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste e Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 6.2,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Verdure Miste e Carne',
        'description' => '',
        'ingredients' => '',
        'price' => 6.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti alla Piastra con Frutti di Mare e Verdure',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Fettuccine di Riso Saltate con Verdure Miste e Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Riso con Pollo al Curry',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Soia con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Spaghetti di Soia con Frutti di Mare',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Gnocchi di Riso con Verdure',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso alla Cantonese',
        'description' => '',
        'ingredients' => '',
        'price' => 3.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso Con Gamberi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Verdure Miste',
        'description' => '',
        'ingredients' => '',
        'price' => 3.5,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso Piccante al Maialino',
        'description' => '',
        'ingredients' => '',
        'price' => 3.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Manzo',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso con Frutti di Mare e Pomodoro',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Riso alla Piastra',
        'description' => 'in salsa satè con frutti di mare',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Pollo in Salsa Limone',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo in Salsa Piccante',
        'description' => '',
        'ingredients' => '',
        'price' => 4.8,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo in Nido di Rondine',
        'description' => '',
        'ingredients' => '',
        'price' => 5.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Pollo ai Peperoni',
        'description' => '',
        'ingredients' => '',
        'price' => 4.9,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Ravioli alla Griglia',
        'description' => 'carne macinata, cipolline e verza',
        'ingredients' => '',
        'price' => 4.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Ravioli Xiaomai di Gamberi',
        'description' => 'gamberi e carne macinata',
        'ingredients' => '',
        'price' => 3.9,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Involtini Primavera',
        'description' => 'farina, verza e carote',
        'ingredients' => '',
        'price' => 1.7,
        'availability' => true,
        'course' => 'Primo',
    ],
    [
        'name' => 'Cornetto Nutella',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Cornetto Frutti di Bosco',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Cornetto Marmellata di Ciliegie',
        'description' => '',
        'ingredients' => '',
        'price' => 1.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Waffle con Sciroppo di Acero',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Sciroppo di Acero',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crepes Marmellata di Limone',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Cioccolato Bianco e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Cioccolato Fondente e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Nutella e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 2.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Nutella e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Pancake con Cioccolato Bianco e Fragole',
        'description' => '',
        'ingredients' => '',
        'price' => 4.5,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Galak',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Kinder Maxi',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Kinder Cereali',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Twix',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe Nutella e Snickers',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Crêpe con Mascarpone',
        'description' => '',
        'ingredients' => '',
        'price' => 4.0,
        'availability' => true,
        'course' => 'Dolce',
    ],
    [
        'name' => 'Classic Burger',
        'description' => '200g hamburger, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Cheeseburger',
        'description' => '200g hamburger, formaggio cheddar, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Bacon Cheeseburger',
        'description' => '200g hamburger, bacon, formaggio cheddar, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 8.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Hamburger Bismarck',
        'description' => '200g hamburger, bacon, formaggio cheddar, uovo all’occhio di bue, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 9.5,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Doppio Cheeseburger',
        'description' => '2 hamburger da 200g, doppio formaggio cheddar, maionese al cetriolo, pomodoro e lattuga',
        'ingredients' => '',
        'price' => 13.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Hamburger Red Hot',
        'description' => '200g hamburger, pecorino semistagionato di pienza, ‘nduja artigianale di spilinga, lattuga e pomodoro',
        'ingredients' => '',
        'price' => 14.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Project Burger',
        'description' => 'hamburger, Parmigiano Reggiano, lattuga, curry mudras e cipolla saltata',
        'ingredients' => '',
        'price' => 12.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Truffle Burger',
        'description' => 'hamburger, caciocavallo al tartufo bianco, bacon, rucola e lattuga',
        'ingredients' => '',
        'price' => 15.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
    [
        'name' => 'Panino Norvegese',
        'description' => 'panino con rosti di patate, salmone norvegese affumicato, lattuga, pomodoro e salsa tzatziki',
        'ingredients' => '',
        'price' => 9.0,
        'availability' => true,
        'course' => 'Secondo',
    ],
];
